### ISSUE TITLE
Build crashes under FreeBSD 12.1

### ISSUE THREAD

**Issue by bobr-kun** [madf/stg#4]
Got numerous errors while building Stragazer under next FreeBSD 12.1 releases:
    FreeBSD 12.1-RELEASE FreeBSD 12.1-RELEASE
    FreeBSD 12.1-RELEASE-p13 FreeBSD 12.1-RELEASE-p13 GENERIC amd64

Trace log part:
> ln -fs "`pwd`/mod_conf_sg.so" /root/stg-2.409/projects/stargazer/modules/mod_conf_sg.so
> gmake[2]: Leaving directory '/root/stg-2.409/projects/stargazer/plugins/configuration/sgconfig'
> gmake  -C other/ping
> gmake[2]: Entering directory '/root/stg-2.409/projects/stargazer/plugins/other/ping'
> g++ -c ping.cpp -I/usr/local/include -DARCH_LE -fPIC -DNDEBUG -DFREE_BSD5 -I /root/stg-2.409/projects/stargazer/../../include -I ../../../../../stglibs/pinger.lib/include -I ../../../../../stglibs/common.lib/include -I ../../../../../stglibs/logger.lib/include -I ../../../../../stglibs/scriptexecuter.lib/include -I /root/stg-2.409/projects/stargazer/../../include -DNDEBUG -DFREE_BSD5
> In file included from ../../../../../stglibs/pinger.lib/include/stg/pinger.h:23,
>                  from ping.h:15,
>                  from ping.cpp:1:
> /usr/include/netinet/in_systm.h:54:9: error: 'u_int16_t' does not name a type; did you mean 'uint16_t'?
>    54 | typedef u_int16_t n_short;  /* short as received from the net */
>       |         ^~~~~~~~~
>       |         uint16_t
> /usr/include/netinet/in_systm.h:55:9: error: 'u_int32_t' does not name a type; did you mean 'uint32_t'?
>    55 | typedef u_int32_t n_long;  /* long as received from the net */
>       |         ^~~~~~~~~
>       |         uint32_t
> /usr/include/netinet/in_systm.h:57:9: error: 'u_int32_t' does not name a type; did you mean 'uint32_t'?
>    57 | typedef u_int32_t n_time;  /* ms since 00:00 UTC, byte rev */
>       |         ^~~~~~~~~
>       |         uint32_t
> In file included from ../../../../../stglibs/pinger.lib/include/stg/pinger.h:24,
>                  from ping.h:15,
>                  from ping.cpp:1:
> /usr/include/netinet/ip.h:53:2: error: 'u_char' does not name a type; did you mean 'putchar'?
>    53 |  u_char ip_hl:4,  /* header length */
>       |  ^~~~~~
>       |  putchar
> /usr/include/netinet/ip.h:60:2: error: 'u_char' does not name a type; did you mean 'putchar'?
>    60 |  u_char ip_tos;   /* type of service */
>       |  ^~~~~~
>       |  putchar
> /usr/include/netinet/ip.h:61:2: error: 'u_short' does not name a type; did you mean 'short'?
>    61 |  u_short ip_len;   /* total length */
>       |  ^~~~~~~
>       |  short
> /usr/include/netinet/ip.h:62:2: error: 'u_short' does not name a type; did you mean 'short'?
>    62 |  u_short ip_id;   /* identification */
>       |  ^~~~~~~
>       |  short
> /usr/include/netinet/ip.h:63:2: error: 'u_short' does not name a type; did you mean 'short'?
>    63 |  u_short ip_off;   /* fragment offset field */
>       |  ^~~~~~~
>       |  short
> /usr/include/netinet/ip.h:68:2: error: 'u_char' does not name a type; did you mean 'putchar'?
>    68 |  u_char ip_ttl;   /* time to live */
>       |  ^~~~~~
>       |  putchar
> /usr/include/netinet/ip.h:69:2: error: 'u_char' does not name a type; did you mean 'putchar'?
>    69 |  u_char ip_p;   /* protocol */
>       |  ^~~~~~
>       |  putchar
> /usr/include/netinet/ip.h:70:2: error: 'u_short' does not name a type; did you mean 'short'?
>    70 |  u_short ip_sum;   /* checksum */
>       |  ^~~~~~~
>       |  short
> /usr/include/netinet/ip.h:174:2: error: 'u_char' does not name a type; did you mean 'putchar'?
>   174 |  u_char ipt_code;  /* IPOPT_TS */
>       |  ^~~~~~
>       |  putchar
> /usr/include/netinet/ip.h:175:2: error: 'u_char' does not name a type; did you mean 'putchar'?
>   175 |  u_char ipt_len;  /* size of structure (variable) */
>       |  ^~~~~~
>       |  putchar
> /usr/include/netinet/ip.h:176:2: error: 'u_char' does not name a type; did you mean 'putchar'?
>   176 |  u_char ipt_ptr;  /* index of current entry */
>       |  ^~~~~~
>       |  putchar
> /usr/include/netinet/ip.h:178:2: error: 'u_char' does not name a type; did you mean 'putchar'?
>   178 |  u_char ipt_flg:4,  /* flags, see below */
>       |  ^~~~~~
>       |  putchar
> /usr/include/netinet/ip.h:225:2: error: 'u_char' does not name a type; did you mean 'putchar'?
>   225 |  u_char  ippseudo_pad; /* pad, must be zero */
>       |  ^~~~~~
>       |  putchar
> /usr/include/netinet/ip.h:226:2: error: 'u_char' does not name a type; did you mean 'putchar'?
>   226 |  u_char  ippseudo_p; /* protocol */
>       |  ^~~~~~
>       |  putchar
> /usr/include/netinet/ip.h:227:2: error: 'u_short' does not name a type; did you mean 'short'?
>   227 |  u_short  ippseudo_len; /* protocol length */
>       |  ^~~~~~~
>       |  short
> In file included from ../../../../../stglibs/pinger.lib/include/stg/pinger.h:25,
>                  from ping.h:15,
>                  from ping.cpp:1:
> /usr/include/netinet/ip_icmp.h:47:2: error: 'u_int32_t' does not name a type; did you mean 'uint32_t'?
>    47 |  u_int32_t ira_addr;
>       |  ^~~~~~~~~
>       |  uint32_t
> /usr/include/netinet/ip_icmp.h:48:2: error: 'u_int32_t' does not name a type; did you mean 'uint32_t'?
>    48 |  u_int32_t ira_preference;
>       |  ^~~~~~~~~
>       |  uint32_t
> /usr/include/netinet/ip_icmp.h:55:2: error: 'u_char' does not name a type; did you mean 'putchar'?
>    55 |  u_char icmp_type;  /* type of message, see below */
>       |  ^~~~~~
>       |  putchar
> /usr/include/netinet/ip_icmp.h:56:2: error: 'u_char' does not name a type; did you mean 'putchar'?
>    56 |  u_char icmp_code;  /* type sub code */
>       |  ^~~~~~
>       |  putchar
> /usr/include/netinet/ip_icmp.h:57:2: error: 'u_short' does not name a type; did you mean 'short'?
>    57 |  u_short icmp_cksum;  /* ones complement cksum of struct */
>       |  ^~~~~~~
>       |  short
> /usr/include/netinet/ip_icmp.h:66:2: error: 'u_char' does not name a type; did you mean 'putchar'?
>    66 |  u_char icmp_type;  /* type of message, see below */
>       |  ^~~~~~
>       |  putchar
> /usr/include/netinet/ip_icmp.h:67:2: error: 'u_char' does not name a type; did you mean 'putchar'?
>    67 |  u_char icmp_code;  /* type sub code */
>       |  ^~~~~~
>       |  putchar
> /usr/include/netinet/ip_icmp.h:68:2: error: 'u_short' does not name a type; did you mean 'short'?
>    68 |  u_short icmp_cksum;  /* ones complement cksum of struct */
>       |  ^~~~~~~
>       |  short
> /usr/include/netinet/ip_icmp.h:70:3: error: 'u_char' does not name a type; did you mean 'putchar'?
>    70 |   u_char ih_pptr;   /* ICMP_PARAMPROB */
>       |   ^~~~~~
>       |   putchar
> /usr/include/netinet/ip_icmp.h:85:4: error: 'u_char' does not name a type; did you mean 'putchar'?
>    85 |    u_char irt_num_addrs;
>       |    ^~~~~~
>       |    putchar
> /usr/include/netinet/ip_icmp.h:86:4: error: 'u_char' does not name a type; did you mean 'putchar'?
>    86 |    u_char irt_wpa;
>       |    ^~~~~~
>       |    putchar
> /usr/include/netinet/ip_icmp.h:87:4: error: 'u_int16_t' does not name a type; did you mean 'uint16_t'?
>    87 |    u_int16_t irt_lifetime;
>       |    ^~~~~~~~~
>       |    uint16_t
> /usr/include/netinet/ip_icmp.h:115:3: error: 'u_int32_t' does not name a type; did you mean 'uint32_t'?
>   115 |   u_int32_t id_mask;
>       |   ^~~~~~~~~
>       |   uint32_t
> In file included from ../../../../../stglibs/pinger.lib/include/stg/pinger.h:26,
>                  from ping.h:15,
>                  from ping.cpp:1:
> /usr/include/netinet/ip_var.h:45:2: error: 'u_char' does not name a type; did you mean 'putchar'?
>    45 |  u_char ih_x1[9];  /* (unused) */
>       |  ^~~~~~
>       |  putchar
> /usr/include/netinet/ip_var.h:46:2: error: 'u_char' does not name a type; did you mean 'putchar'?
>    46 |  u_char ih_pr;   /* protocol */
>       |  ^~~~~~
>       |  putchar
> /usr/include/netinet/ip_var.h:47:2: error: 'u_short' does not name a type; did you mean 'short'?
>    47 |  u_short ih_len;   /* protocol length */
>       |  ^~~~~~~
>       |  short
> gmake[2]: *** [deps:44: ping.o] Error 1
> gmake[2]: Leaving directory '/root/stg-2.409/projects/stargazer/plugins/other/ping'
> gmake[1]: *** [Makefile:13: other/ping] Error 2
> gmake[1]: Leaving directory '/root/stg-2.409/projects/stargazer/plugins'
> gmake: *** [Makefile:64: plugins] Error 2

Provided fix in PR #3

**Comment by madf** [comment]
I guess, this is no longer a problem. Consider closing.

**Comment by madf** [comment]
No reply from @bobr-kun for too long, closing.

**Comment by nightflyza** [comment]
Oh shi~
he is here too :)
